# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Citing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('cited_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date of citation')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('is_my', models.BooleanField(default=True)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('last_modified_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date last modified')),
                ('deleted', models.BooleanField(default=False)),
                ('citations', models.ManyToManyField(through='cites.Citation', to='cites.Citing')),
            ],
        ),
        migrations.AddField(
            model_name='citation',
            name='citing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cites.Citing'),
        ),
        migrations.AddField(
            model_name='citation',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cites.Publication'),
        ),
    ]
