# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 16:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 17, 16, 8, 13, 885115, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='citation',
            name='cited_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 17, 16, 8, 13, 891171, tzinfo=utc), verbose_name='date of citation'),
        ),
        migrations.AlterField(
            model_name='citation',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 17, 16, 8, 13, 891197, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='citing',
            name='cited_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 17, 16, 8, 13, 890546, tzinfo=utc), verbose_name='date of citation'),
        ),
        migrations.AlterField(
            model_name='citing',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 17, 16, 8, 13, 890575, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 17, 16, 8, 13, 885147, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='is_my',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='last_modified_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 17, 16, 8, 13, 885166, tzinfo=utc), verbose_name='date last modified'),
        ),
    ]
