# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 16:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cites', '0002_auto_20170317_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='cited_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 17, 16, 8, 51, 919935, tzinfo=utc), verbose_name='date of citation'),
        ),
        migrations.AlterField(
            model_name='citation',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 17, 16, 8, 51, 919975, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='citing',
            name='cited_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 17, 16, 8, 51, 918985, tzinfo=utc), verbose_name='date of citation'),
        ),
        migrations.AlterField(
            model_name='citing',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 17, 16, 8, 51, 919027, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 17, 16, 8, 51, 910875, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='last_modified_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 17, 16, 8, 51, 910908, tzinfo=utc), verbose_name='date last modified'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 17, 16, 8, 51, 910830, tzinfo=utc), verbose_name='date published'),
        ),
    ]
