# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 21:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cites', '0002_publication_abbrev'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='is_my',
        ),
    ]
