# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 16:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cites', '0003_auto_20170317_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citing',
            name='cited_publication',
        ),
        migrations.AddField(
            model_name='publication',
            name='citing',
            field=models.ManyToManyField(through='cites.Citation', to='cites.Citing'),
        ),
        migrations.AlterField(
            model_name='citation',
            name='cited_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 17, 16, 34, 35, 152534, tzinfo=utc), verbose_name='date of citation'),
        ),
        migrations.AlterField(
            model_name='citation',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 17, 16, 34, 35, 152565, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='citing',
            name='cited_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 17, 16, 34, 35, 145723, tzinfo=utc), verbose_name='date of citation'),
        ),
        migrations.AlterField(
            model_name='citing',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 17, 16, 34, 35, 145763, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 17, 16, 34, 35, 151782, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='last_modified_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 17, 16, 34, 35, 151803, tzinfo=utc), verbose_name='date last modified'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 17, 16, 34, 35, 151751, tzinfo=utc), verbose_name='date published'),
        ),
    ]
