# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 21:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cites', '0004_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Citing',
            new_name='CitationNew',
        ),
        migrations.RenameModel(
            old_name='Citation',
            new_name='PublicationCitation',
        ),
        migrations.RenameField(
            model_name='publicationcitation',
            old_name='citing',
            new_name='citation',
        ),
    ]
