# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 21:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cites', '0005_auto_20170320_2240'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CitationNew',
            new_name='Citation',
        ),
    ]
