# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 16:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cites', '0005_auto_20170317_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='citing',
            new_name='citations',
        ),
    ]
