# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cites', '0006_auto_20170320_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cites.Author')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cites.Publication')),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='authors',
            field=models.ManyToManyField(through='cites.PublicationAuthor', to='cites.Author'),
        ),
    ]
